import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Doqr Teste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flow overflow-hidden top-0 fixed z-10 flex flex-row h-[10%] w-full bg-background shadow-sm border-b-2">
          <div className="flex flex-row items-center justify-between flex-1 px-2 md:px-10">
            <div className="w-full items-center flex gap-4 flex-row">
              {/* <h1 className="text-background flex p-1 rounded-md text-xl bg-primary font-bold"> */}
              {/* TD */}
              <Image
                className="text-background flex p-2 rounded-lg bg-primary font-bold"
                alt="doQr_logo"
                src={"https://www.doqr.com.br/icons/logoHeader.svg"}
                width="110"
                height="110"
              />

              {/* </h1> */}
              <h1 className="text-text text-xl font-bold">
                <u>Teste Doqr </u>
              </h1>
            </div>
            <div className="w-full items-center justify-end flex gap-4 flex-row">
              <Image
                className="text-background flex rounded-full bg-primary font-bold border-2 border-text/70"
                alt="profile_image"
                src={
                  "https://media.licdn.com/dms/image/v2/D4D03AQEtgmBAsZG-Qw/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1711324840740?e=1733961600&v=beta&t=0xbOK02u42N6GxLSpTwmya1gPU8Ry8RSiQ47E1n3TX4"
                }
                width="35"
                height="35"
              />
              <h1 className="text-text md:text-lg font-bold">
                Gabriel Rodrigues
              </h1>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
